class Kite < Formula
  desc "Universal webhook adapter CLI"
  homepage "https://github.com/Alpha-Centauri-Cyberspace/kite-cli"
  version "0.0.0"
  license "MIT"

  # This file is regenerated by kite-cli's `publish-homebrew.yml` workflow
  # on every release. The placeholder values below are overwritten with real
  # R2 URLs and SHA256s once kite-cli cuts its first tagged release.

  on_macos do
    on_arm do
      url "https://example.invalid/kite-darwin-arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_intel do
      url "https://example.invalid/kite-linux-x86_64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "kite"
  end

  test do
    assert_match "kite", shell_output("#{bin}/kite --version")
  end
end
